// Learning Records
export const FETCH_LEARNING_RECORDS = `FETCH_LEARNING_RECORDS`;
export const FETCH_LEARNING_RECORDS_END = `FETCH_LEARNING_RECORDS_END`;
export const FETCH_LEARNING_RECORDS_ERROR = `FETCH_LEARNING_RECORDS_ERROR`;
